name: Laravel + React CI/CD

on:
  push:
    branches: [ main ]
  

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Generate key
        run: php artisan key:generate

      - name: Install Node dependencies
        run: npm ci

      - name: Build React (Vite)
        run: npm run dev

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
           - name: npm test
        

      
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        
